### PR TITLE
update to latest idb-wrapper closes #38

### LINKED ISSUE #38: please update idb-wrapper to latest
idb-wrapper now detects if shimIndexedDB is set.

So using `level-js` with [IndexedDBShim](https://github.com/axemclion/IndexedDBShim) works better in environments only supporting webSQL.

iOS 8 homescreen - I'm looking at you!

### PR DESCRIPTION
**Pull request by JamesKyburz**

### CODE REVIEW

**Comment by juliangruber** [comment]
lgtm

**Comment by JamesKyburz** [comment]
Any change of this getting merged?

**Comment by jprichardson** [comment]
:+1:

**Comment by maxogden** [comment]
sorry it took so long. published as 2.2.0

**Pull request merged**
