### PR TITLE
properly extend idb options

### PR DESCRIPTION
**Pull request by timkuijsten**
xtend now really extends

### CODE REVIEW

**Comment by timkuijsten** [comment]
https://github.com/maxogden/level.js/blob/d18297a9d5fba18721f341eb03f30038dc5d2562/index.js#L81-L85 has never been executed because [options.valueEncoding](https://github.com/maxogden/level.js/blob/d18297a9d5fba18721f341eb03f30038dc5d2562/index.js#L79) has never been available.

**Comment by mcollina** [comment]
Would you mind adding a unit test?

**Comment by timkuijsten** [comment]
There are lot's of failures while running npm test and I have a hard time finding the correct place and see if it succeeds. Should it be something like this?

```
diff --git a/test/custom-tests.js b/test/custom-tests.js
index f6b801b..754cb1a 100644
--- a/test/custom-tests.js
+++ b/test/custom-tests.js
@@ -27,6 +27,16 @@ module.exports.all = function(leveljs, tape, testCommon) {
       })
     })
   })
+
+  tape('test database open, options and callback', function (t) {
+    levelup('options-test', {db: leveljs, valueEncoding: 'hex'}, function (err, db) {
+      t.notOk(err, 'no error')
+      t.equal(db.IDBOptions.valueEncoding, 'hex', 'options merged')
+      db.close(function () {
+        t.end()
+      })
+    })
+  })
   
   // NOTE: in chrome (at least) indexeddb gets buggy if you try and destroy a db,
   // then create it again, then try and destroy it again. these avoid doing that
```

**Comment by timkuijsten** [comment]
ps. the aforementioned case for [L81-L85](https://github.com/maxogden/level.js/blob/d18297a9d5fba18721f341eb03f30038dc5d2562/index.js#L81-L85) won't change since the options parameter in put, del and get does not contain the constructor options.

**Comment by timkuijsten** [comment]
Let's put this on hold, the fact that idb options have never been part of the public api might come in handy when we start gutting out idb-wrapper.

**Pull request closed without merging**
